name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.12.0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build dist
        run:  ./build.sh
      - name: Zip
        run: (cd dist; zip -r engine-${{ github.ref_name }}.zip bin lib pages)
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/engine-${{ github.ref_name }}.zip
